title: Pinocchio
description: Fast Forward Inverse Dynamic for Multibody Systems
baseurl: "/pinocchio"
github-url: "https://github.com/stack-of-tasks/pinocchio"
remote_theme: Gepetto/jekyll-theme
markdown: kramdown

category_list:
  - name: Getting Started
    icon: graduation-cap
    links:
      - name: Tutorials
        url: https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/md_doc_d-practical-exercises_intro.html

link_list:
  - name: Documentation
    icon: book
    url: https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/
  - name: Development
    icon: github
    url: http://www.github.com/stack-of-tasks/pinocchio
